### ISSUE TITLE
Redesign the Movies page to match the new designs

### ISSUE THREAD

**Issue by RuthwikHM** [Joshi-Karan/MovieRecommender_Fall24#6]
Redesign the existing movies page(screenshot attached) to match the new design we are utilising. 
<img width="1667" alt="Screenshot 2024-10-26 at 12 20 20" src="https://github.com/user-attachments/assets/fadfd9f9-203c-4ddb-8e1f-36d8844eb3be">

**Comment by asvch** [comment]
Update:
![image](https://github.com/user-attachments/assets/932de4d8-dbed-4df4-97ed-8e4867c52aab)
